---
dependency:
  name: galaxy
driver:
  name: gce
# lint: |
#   set -e
#   yamllint .
#   ansible-lint .
platforms:
  - name: gcp-gce-ubuntu
    zone: us-west1-a
    machine_type: n1-standard-8
    image: ubuntu-2004-lts
provisioner:
  name: ansible
verifier:
  name: ansible
