---
# Reference: https://yamllint.readthedocs.io/en/stable/configuration.html
yaml-files:
- '*.yaml'
- '*.yml'
- '.yamllint'

extends: default

rules:
  indentation:
    spaces: 2
    indent-sequences: false
  line-length: disable
  new-line-at-end-of-file: disable
