---

# Removes ABM from targeted machines and unregisters from GKE Hub

# NOTE: must specify `--tags never` on the CLI to run this

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  pre_tasks:
  - name: Download SSH key
    include_role:
      name: download-ssh-key
  - name: Gathering Facts
    setup: {}
    tags:
    - always
  - name: Populate service facts
    service_facts:
    tags:
    - always
  roles:
  - abm-remove
  vars: []
  tags:
  - hardware
