---

# This playbook is used to run post-installation of the solution, typically for bug fixes and little changes
- hosts: all
  gather_facts: false
  become: true
  become_user: root
  pre_tasks:
  - name: Download SSH key
    include_role:
      name: download-ssh-key
  - name: Gathering Facts
    setup: {}
    tags:
    - always
  - name: Populate service facts
    service_facts:
    tags:
    - always
  roles:
  - validate
  - abm-post-install
  - update-automation
  vars:
    kubeconfig_shared_location: "{{ abm_install_folder }}/kubeconfig/kubeconfig"
