---

# Setup everything and install ABM (but not install software on top)
- hosts: cloud_type_abm
  become: true
  become_user: root
  roles:
  - validate
  - google-tools
  - update-automation
  - ready-linux
  - setup-kvm
  - abm-install
  - abm-software
  - abm-post-install
  - abm-login-token
  vars: []
  tags:
  - cloud
