---

# Installs Anthos Bare Metal on all inventory
- hosts: workers
  become: true
  become_user: root
  roles:
    - validate
    - google-tools
    - update-automation
    - ready-linux
    - setup-kvm
    - abm-install
    - abm-software
    - abm-post-install
    - abm-login-token
  vars: []
  tags:
    - hardware
