
## Vars specifically for CNUC1

# Name of the cluster
cluster_name: "cnuc-1"
# Used for logging/metrics
machine_label: "cnuc-3"

# This machine's IP
node_ip: "10.200.0.4"

# Ansible Pull Authenticaiton String
ansible_pull_authentication_string: "{{scm_token_user}}:{{scm_token_token}}@"

# Ansible Pull repo for Remote Execution
ansible_pull_remote_execute_repo: "https://{{ ansible_pull_authentication_string | default('', true) }}gitlab.com/gcp-solutions-public/retail-edge/remote-command-repo.git"

# Ansible pull repo to manage simplified drift
ansible_pull_drift_repo: "https://{{ ansible_pull_authentication_string | default('', true) }}gitlab.com/gcp-solutions-public/retail-edge/drift-repo.git"

google_region: "us-west1"
google_zone: "us-west1-b"
