---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # - name: ubuntu2010
  #   image: docker.io/ubuntu:20.10
  #   pre_build_image: true
  - name: buster
    image: docker.io/python:3-buster
    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible
