
- name: Prepare
  hosts: all
  gather_facts: false
  vars: []

  tasks:
  - name: Uninstall packages
    apt:
      pkg:
        - bash-completion
      state: present
      force: yes
      purge: yes
    tags:
    - molecule-prepare
    when:
    - target_os == "ubuntu"

  - name: Uninstall packages
    dnf:
      pkg:
        - bash-completion
      state: present
      force: yes
      purge: yes
    tags:
    - molecule-prepare
    when:
    - target_os == "redhat"
