

# GSA Created and granted permissions in `all.yaml`
root_repository_service_account_email: source-repo-agent-{{ cluster_name }}@{{ google_service_account_project_id }}.iam.gserviceaccount.com

# NOTE: This is a tight coupling with the "Root Repo" that contains "ExternalSecret" instances with the `git-creds` name
#       IF changed, both the ACM root-repo and this field need to match
root_repository_git_secret_name: "git-creds"

# This is the production project that contains the CDI containers. Need it to replace with the staging dynamically in file (FIXME: This is deprecated)
cdi_staging_project: "anthos-baremetal-release"

# Snapshot: Where to place configuration
snapshot_config_folder: "{{ abm_install_folder }}/snapshots"
snapshot_config_file: "{{ snapshot_config_folder }}/snapshot-config.yaml"
# Output of snapshot (if not uploading??? ) # TODO: Revist this, may not need
snapshot_output_folder: "{{ snapshot_config_folder }}/snapshots/output"

# CDI add CPU Monitoring flag script run by cron.d
cdi_cron_script_file: "{{ abm_install_folder }}/cdi-check-node.sh"

# Location of SDS configuration files
sds_config_files: "{{ abm_install_folder }}/sds-configs"
