---
# vars file for abm-install

# Edge API
edge_api_enabled: false
edge_api_location: us-central1 # same as cloud-ops region {{ google_region }}, but hard-coded as API is only in us-central1

# User that has sudo, password less SSH access to node_ip
abm_install_user: "el-gato"

# Cluster Configuration
install_type: standalone
multi_network_enabled: "{{ enable_multus_network | default('false', True) }}"
enable_application_logging: true
dataplane_v2: false # primarily vSphere installs

# Skip preflight checks?
skip_preflight: false

# Cluster IP Ranges
pod_cidr: "172.16.0.0/16"
services_cidr: "192.168.30.0/23"

# Cluster Persistant Volumes (outside of overlay storage options)
local_pvc_mount: "/opt/pvc-disk"
local_share_pvc_mount: "/opt/localpv-share" # Default value

# Cluster runtime
container_runtime: "containerd" # docker or containerd

# How long to let the ABM installation (via bmctl) take before an Ansible timeout occurs. Default 120 min
abm_install_sync_timeout_seconds: 18000
abm_install_sync_poll_seconds: 60