
- name: Prompt reminding about tags
  debug:
    msg: "IF you are trying to run this and do not see any progress, perhaps you forgot the '--tags never'"  # must specify `--tags never` on the CLI to run this
  tags:
    - abm-remove

- name: Check if abm-installation folder exists
  stat:
    path: "{{ abm_workspace_folder }}"
  register: has_abm_workspace
  tags:
    - check-abm-remove
    - never

- name: Remove the ABM cluster with cloud and local
  import_tasks: remove-abm.yaml
  when:
  - has_abm_workspace is defined
  - has_abm_workspace.stat.exists
  - has_abm_workspace.stat.isdir
  tags:
    - abm-remove
    - never

- name: Archive current cluster snapshots
  import_tasks: remove-snapshot.yaml
  when:
    - (primary_cluster_machine is defined)
    - (primary_cluster_machine == true)
  tags:
    - snapshot-remove
    - never

- name: Remove ABM Workspace
  ansible.builtin.file:
    path: "{{ abm_install_folder }}/bmctl-workspace"
    state: absent
  tags:
    - abm-remove
    - never
