# Archive old snapshots

- name: Buckets List initialization
  set_fact:
    buckets: []

- name: Get a list of current snapshots
  ignore_errors: true
  command:
    cmd: "gsutil ls -p {{ google_project_id }} gs://{{ snapshot_gcs_bucket_base }}/*.tar.gz"
  register: snapshot_list
  when:
    - primary_cluster_machine is defined
    - primary_cluster_machine == True

- name: split bucket information
  set_fact:
    buckets: "{{ buckets + [ item | regex_search('^(gs:)\/\/([a-zA-Z0-9.\\-_]{1,255})\/([a-z0-9-]+)\/([a-z0-9-.TZ]+)', '\\2', '\\3', '\\4') ] }}"
  with_items:
  - "{{ snapshot_list.stdout_lines }}"
  when:
    - snapshot_list.rc == 0 # only on success (there are items)
    - primary_cluster_machine is defined
    - primary_cluster_machine == True

- name: Archive snapshots to archive folder
  command:
    cmd: "gsutil mv gs://{{ item[0] }}/{{ item[1] }}/{{ item[2] }} gs://{{ item[0] }}/{{ item[1] }}/archive/{{ item[2] }}"
  with_items:
  - "{{ buckets }}"
  when:
    - primary_cluster_machine is defined
    - primary_cluster_machine == True
    - buckets is defined and (buckets | length>0 )
