- name: Remove any previous Docker version
  shell: |
    sudo dnf remove docker \
    docker-client \
    docker-client-latest \
    docker-common \
    docker-latest \
    docker-latest-logrotate \
    docker-logrotate \
    docker-engine

- name: Remove podman man pages
  shell: |
    sudo dnf remove podman-manpages

- name: Install Docker 19.03+
  shell: |
    sudo dnf install -y yum-utils
    sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    sudo dnf install -y --allowerasing docker-ce docker-ce-cli containerd.io
    sudo systemctl start docker
    sudo docker version